import { existsSync, readdirSync, statSync, writeFileSync } from "node:fs";

const cookbookRoot = `${import.meta.dir}/..`;
const demosDir = `${cookbookRoot}/src/demos`;

const slugs = existsSync(demosDir)
  ? readdirSync(demosDir).filter((name) => {
      const p = `${demosDir}/${name}`;
      return statSync(p).isDirectory() && existsSync(`${p}/help.ts`);
    })
  : [];

const helpImports = slugs
  .map((slug, i) => `import help${i} from "../demos/${slug}/help.ts";`)
  .join("\n");

// Biome groups imports without blank lines between adjacent import statements.
// Type-only imports sort after value imports alphabetically by source.
const importsBlock =
  helpImports.length > 0
    ? `${helpImports}\nimport type { DemoHelp } from "./help-types.ts";`
    : `import type { DemoHelp } from "./help-types.ts";`;

const entries = slugs
  .map((slug, i) => `{ slug: "${slug}", help: help${i} }`)
  .join(", ");

const demosLiteral =
  entries.length > 0
    ? `export const demos: DemoEntry[] = [${entries}];`
    : `export const demos: DemoEntry[] = [];`;

const out = `// AUTO-GENERATED by scripts/generate-help-manifest.ts. Do not edit by hand.
${importsBlock}

export type DemoEntry = { slug: string; help: DemoHelp };

${demosLiteral}
`;

writeFileSync(`${cookbookRoot}/src/shared/demos-manifest.ts`, out);
console.log(
  `[furnace/cookbook] generated manifest with ${slugs.length} demo(s)`,
);
