import { existsSync, readdirSync, statSync, writeFileSync } from "node:fs";

const cookbookRoot = `${import.meta.dir}/..`;
const demosDir = `${cookbookRoot}/src/demos`;

const slugs = existsSync(demosDir)
  ? readdirSync(demosDir).filter((name) => {
      const p = `${demosDir}/${name}`;
      return statSync(p).isDirectory() && existsSync(`${p}/help.ts`);
    })
  : [];

const importsBlock = slugs
  .map((slug, i) => `import help${i} from "../demos/${slug}/help.ts";\n`)
  .join("");

const entriesBlock = slugs
  .map((slug, i) => `  { slug: "${slug}", help: help${i} },\n`)
  .join("");

const demosLiteral =
  entriesBlock.length > 0
    ? `export const demos: DemoEntry[] = [\n${entriesBlock}];\n`
    : `export const demos: DemoEntry[] = [];\n`;

const importsPrefix = importsBlock.length > 0 ? `${importsBlock}\n` : "";

const out = `// AUTO-GENERATED by scripts/generate-help-manifest.ts. Do not edit by hand.
import type { DemoHelp } from "./help-types.ts";

${importsPrefix}export type DemoEntry = { slug: string; help: DemoHelp };

${demosLiteral}`;

writeFileSync(`${cookbookRoot}/src/shared/demos-manifest.ts`, out);
console.log(
  `[furnace/cookbook] generated manifest with ${slugs.length} demo(s)`,
);
