import { existsSync, readdirSync, statSync, writeFileSync } from "node:fs";

const cookbookRoot = `${import.meta.dir}/..`;
const demosDir = `${cookbookRoot}/src/demos`;

// Sorted by slug so Biome's organize-imports rule doesn't fight the output.
// Each slug gets a stable identifier `help_<slug-with-hyphens-as-underscores>`
// keyed off the path itself, so adding or removing demos never renumbers
// unrelated imports.
const slugs = existsSync(demosDir)
  ? readdirSync(demosDir)
      .filter((name) => {
        const p = `${demosDir}/${name}`;
        return statSync(p).isDirectory() && existsSync(`${p}/help.ts`);
      })
      .sort()
  : [];

const identFor = (slug: string): string => `help_${slug.replace(/-/g, "_")}`;

const helpImports = slugs
  .map((slug) => `import ${identFor(slug)} from "../demos/${slug}/help.ts";`)
  .join("\n");

// Biome groups imports without blank lines between adjacent import statements.
// Type-only imports sort after value imports alphabetically by source.
const importsBlock =
  helpImports.length > 0
    ? `${helpImports}\nimport type { DemoHelp } from "./help-types.ts";`
    : `import type { DemoHelp } from "./help-types.ts";`;

// Emit one entry per line so Biome's formatter doesn't reflow on the next run.
const entriesBlock = slugs
  .map((slug) => `  { slug: "${slug}", help: ${identFor(slug)} },`)
  .join("\n");

const demosLiteral =
  slugs.length > 0
    ? `export const demos: DemoEntry[] = [\n${entriesBlock}\n];`
    : `export const demos: DemoEntry[] = [];`;

const out = `// AUTO-GENERATED by scripts/generate-help-manifest.ts. Do not edit by hand.
${importsBlock}

export type DemoEntry = { slug: string; help: DemoHelp };

${demosLiteral}
`;

writeFileSync(`${cookbookRoot}/src/shared/demos-manifest.ts`, out);
console.log(
  `[furnace/cookbook] generated manifest with ${slugs.length} demo(s)`,
);
