//! Emits `.furnace/shell/furnace_config.rs` — Rust constants baked from
//! `furnace.config.json` so the consumer's shell `main.rs` can apply them to
//! `AppConfig` without runtime parsing or extra deps in `furnace-runtime`.

use crate::config::FurnaceConfig;
use anyhow::{Context, Result};
use std::path::Path;

pub fn emit_shell_config(shell_dir: &Path, config: &FurnaceConfig) -> Result<()> {
    let path = shell_dir.join("furnace_config.rs");
    let content = format!(
        "// Generated by furnace CLI. Do not edit by hand.\n\
         pub const WINDOW_TITLE: &str = {title:?};\n\
         pub const WINDOW_WIDTH: f64 = {width}.0;\n\
         pub const WINDOW_HEIGHT: f64 = {height}.0;\n\
         pub const WINDOW_FULLSCREEN: bool = {fullscreen};\n",
        title = config.window.title,
        width = config.window.width,
        height = config.window.height,
        fullscreen = config.window.fullscreen,
    );
    std::fs::write(&path, content)
        .with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}
