use anyhow::{bail, Context, Result};
use std::path::Path;
use std::process::Command;

pub struct WasmRequest<'a> {
    pub crate_path: &'a Path,
    pub out_dir: &'a Path,
    pub release: bool,
}

pub fn compile(req: WasmRequest<'_>) -> Result<()> {
    std::fs::create_dir_all(req.out_dir)?;
    let mut cmd = Command::new("wasm-pack");
    cmd.args(["build", "--target", "bundler", "--out-dir"])
        .arg(req.out_dir)
        .arg(req.crate_path);
    if !req.release {
        cmd.arg("--dev");
    }
    let status = cmd
        .status()
        .context("failed to invoke wasm-pack — is it installed?")?;
    if !status.success() {
        bail!("wasm-pack failed for {}", req.crate_path.display());
    }
    rewrite_wrapper(req.out_dir, req.crate_path)?;
    Ok(())
}

fn rewrite_wrapper(out_dir: &Path, crate_path: &Path) -> Result<()> {
    let cargo_toml = crate_path.join("Cargo.toml");
    let raw = std::fs::read_to_string(&cargo_toml)
        .with_context(|| format!("reading {}", cargo_toml.display()))?;
    let name = parse_package_name(&raw)
        .with_context(|| format!("no package.name in {}", cargo_toml.display()))?;
    let snake = name.replace('-', "_");

    let js_path = out_dir.join(format!("{snake}.js"));
    let dts_path = out_dir.join(format!("{snake}.d.ts"));

    let js = format!(
        r#"// AUTO-GENERATED BY furnace — DO NOT EDIT
// Bun-compatible wasm-bindgen wrapper. Replaces the wasm-pack default
// which assumes webpack-style split-files instantiation that Bun's
// bundler doesn't perform. Await `ready` before calling any exported
// function.

import wasmUrl from "./{snake}_bg.wasm";
import * as glue from "./{snake}_bg.js";

export * from "./{snake}_bg.js";

export const ready = (async () => {{
  const {{ instance }} = await WebAssembly.instantiateStreaming(
    fetch(wasmUrl),
    {{ "./{snake}_bg.js": glue }},
  );
  glue.__wbg_set_wasm(instance.exports);
  const start = instance.exports.__wbindgen_start;
  if (typeof start === "function") start();
}})();
"#
    );

    let dts = format!(
        r#"/* AUTO-GENERATED BY furnace — DO NOT EDIT */
export * from "./{snake}_bg.js";
export const ready: Promise<void>;
"#
    );

    std::fs::write(&js_path, js)?;
    std::fs::write(&dts_path, dts)?;
    Ok(())
}

fn parse_package_name(toml: &str) -> Option<String> {
    let mut in_package = false;
    for line in toml.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') {
            in_package = trimmed == "[package]";
            continue;
        }
        if !in_package {
            continue;
        }
        if let Some(rest) = trimmed.strip_prefix("name") {
            let rest = rest.trim_start().strip_prefix('=')?.trim_start();
            return rest
                .strip_prefix('"')
                .and_then(|s| s.strip_suffix('"'))
                .map(|s| s.to_string());
        }
    }
    None
}
