/**
 * Embedded pin decal texture as a base64 data URL.
 *
 * 64x64 RGBA PNG: diagonal rainbow stripes.
 * Generated by: bun packages/hello-world/scripts/gen-decal.ts
 * Verified:     file /tmp/decal.png → PNG image data, 64 x 64, 8-bit/color RGBA
 *
 * Using a data URL (not a served file) so it works in dev:web, build:web,
 * and dev:native without any serving wiring — fetch(dataUrl) exercises the
 * full decode path via createImageBitmap.
 */
export const DECAL_DATA_URL =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAABLElEQVR4nOXQuxECMQwAUdV0sYsgpiaKoAhi4osvJr42YGQGMxp9nHuDLeCtvFp7l922smOva49L2fbcy9r1KLu3uvM8y4SMV6OQ8fkACD4eAML7ATC8HQDE/wdA8d8BYPx0wOp4NQoZnw6g4MMBJLwbQMObAUT8GEDF9wFk/HTA6ng1ChmfDqDgwwEkvBtAw5sBRPwYQMX3AWT8dMDqeDUKGZ8OoODDASS8G0DDmwFE/BhAxfcBZPx0wOp4NQoZnw6g4MMBJLwbQMObAUT8GEDF9wFk/HTA6ng1ChmfDqDgwwEkvBtAw5sBRPwYQMX3AWT8dMDqeDUKGZ8OoODDASS8G0DDmwFE/BhAxfcBZPx0wOp4NQoZnw6g4MMBJLwbQMObAUT8+RtAxav9AwJc5nfRQrI7AAAAAElFTkSuQmCC";
